name=Lpf2
version=2.5.0
author=Rbel12b <https://github.com/Rbel12b>
maintainer=Rbel12b <https://github.com/Rbel12b>
sentence=A library for controlling and emulating LEGO Power Functions 2.0 devices (hubs, motors, sensors...) with an esp32
paragraph=Drive physical LPF2 devices over UART (Local::Port), control motors and read sensors attached to LEGO Hubs over BLE (Remote::Port), emulate a full LEGO Hub (HubEmulation), or present the ESP32 itself as a custom LPF2 device to any host hub (Local::EmulatedPort).
category=Device Control
url=https://github.com/Rbel12b/Lpf2.git
architectures=esp32
depends=NimBLE-Arduino