; =====================================================================
; SHARED CONFIGURATION (Applies to all boards automatically)
; =====================================================================
[env]
framework = arduino
monitor_speed = 981200
monitor_filters = esp32_exception_decoder, time

build_flags =
    -DCORE_DEBUG_LEVEL=3                     ; 3 = Info level for general Arduino/ESP system status
    -DLPF2_LOG_LEVEL=4                       ; Match it to Info level for the LEGO library
    -DCONFIG_LPF2_LOG_LEVEL=4                 ; compile in up to DEBUG
    -DARDUINO_USB_CDC_ON_BOOT=1              ; Force everything to the USB cable
    -DCONFIG_ESP_CONSOLE_UART_CUSTOM=1       ; Tells the chip NOT to use default UART0 pins
    -DCONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=1   ; Ensures lowest-level ESP system logs use USB too
    -DCONFIG_ARDUHAL_LOG_COLORS=1            ; Makes errors red, warnings yellow, and info green
    -std=gnu++2a                             ; Keeps your modern C++ capabilities active
    -DLPF2_USE_ARDUINO_SERIAL                ; Force library to use standard Arduino HardwareSerial
    
build_unflags = -std=gnu++11

lib_deps =
;    rbel12b/Lpf2
    h2zero/NimBLE-Arduino@^2.5.0
    adafruit/Adafruit NeoPixel@^1.11.0


; =====================================================================
; BOARD 1: Seeed Xiao ESP32-S3
; =====================================================================
[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
build_flags = 
    ${env.build_flags}                      ; Inherit global flags
    -DUSING_XIAO
    -DBOARD_HAS_PSRAM                        ; XIAO has PSRAM

; =====================================================================
; BOARD 2: Waveshare ESP32-S3-Zero
; =====================================================================
[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.flash_mode = qio
board_build.partitions = default.csv
build_flags = 
    ${env.build_flags}                      ; Inherit global flags
    -DUSING_S3_ZERO
    ; No PSRAM flag here (S3-Zero typically has no PSRAM)

; =====================================================================
; BOARD 3: ESP32-S3 Super Mini
; =====================================================================
[env:esp32-s3-super-mini]
platform = espressif32
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.flash_mode = dio             ; Super Mini uses DIO flash mode for stability
board_build.partitions = default.csv
build_flags = 
    ${env.build_flags}                      ; Inherit global flags
    -DUSING_SUPERMINI
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue          ; Compiler safety flag for early silicon revisions
board_build.psram_type = qio
