import os

# Define the file names
log_filename = "clean_lego_log.txt"
output_filename = "parsed_results.txt"

def parse_lego_hex(time_stamp, opcode, hex_str):
    if not hex_str.strip():
        return f"[{time_stamp}] APP -> HUB (Handshake Trigger) | Opcode: {opcode} | Waiting for Hub..."

    try:
        b = bytes.fromhex(hex_str)
    except ValueError:
        return f"[{time_stamp}] Error parsing hex string: {hex_str}"

    if len(b) < 3:
        return f"[{time_stamp}] Packet too short."

    msg_type = b[2]

    # Handle App to Hub Commands
    if opcode in ["0x52", "0x12"]:
        style = "Critical Setup Request" if opcode == "0x12" else "Fast Motor/LED Command"
        return f"[{time_stamp}] APP -> HUB ({style}) | Message Type: 0x{msg_type:02x} | Raw: {hex_str}"

    # Handle Hub to App Notifications (Sensor Data)
    elif opcode == "0x1b":
        # Look specifically for Combined Mode Port Values (0x46)
        if msg_type == 0x46 and len(b) >= 8:
            port = b[3]
            return f"[{time_stamp}] HUB -> APP | Port {port} Motor Feedback -> Raw Payload: {hex_str}"
        
        # Check for general Hub Alerts/Actions (0x01) like battery or button events
        elif msg_type == 0x01:
            return f"[{time_stamp}] HUB -> APP | Hub Status/Button Alert | Raw Data: {hex_str[6:]}"
            
        return f"[{time_stamp}] HUB -> APP | Other Notification (Type: 0x{msg_type:02x}) | Raw: {hex_str}"

    return f"[{time_stamp}] Unknown Opcode {opcode} | Raw: {hex_str}"

# Main execution block
if not os.path.exists(log_filename):
    print(f"Error: Could not find '{log_filename}' in this folder.")
else:
    print(f"--- Parsing Data from {log_filename} ---")
    print(f"Saving results directly to: {output_filename}")
    
    # Using 'utf-16' to read PowerShell's file output smoothly
    with open(log_filename, "r", encoding="utf-16") as infile, \
         open(output_filename, "w", encoding="utf-8") as outfile:
        
        for line in infile:
            if not line.strip():
                continue
            
            # Split out columns generated by Tshark tabs
            parts = line.strip().split("\t")
            
            if len(parts) == 3:
                time_stamp, opcode, hex_value = parts
            elif len(parts) == 2:
                time_stamp, opcode = parts
                hex_value = ""
            else:
                continue
                
            decoded_text = parse_lego_hex(time_stamp, opcode, hex_value)
            outfile.write(decoded_text + "\n")
                
    print("Done! File saved successfully.")